#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS:
#+LATEX_HEADER:
#+LATEX_HEADER_EXTRA:
#+DESCRIPTION:
#+KEYWORDS:
#+SUBTITLE:
#+LATEX_COMPILER: pdflatex
#+DATE: \today

#+OPTIONS: ^:nil

* Use Case: Waypoint Updater providing final_waypoints

** Work-flow

   To build Waypoint_Updater:

   #+NAME:
   #+BEGIN_SRC shell
     cd ros
     catkin_make
   #+END_SRC

In a separate shell:
#+NAME:
#+BEGIN_SRC shell
source devel/setup.sh
rostopic echo /final_waypoints
#+END_SRC
expect to see the published final_waypoints.

In a separate shell:
#+NAME:
#+BEGIN_SRC shell
source devel/setup.sh
roslaunch launch/styx.launch
#+END_SRC

In a separate shell, start the car simulator:

#+NAME:
#+BEGIN_SRC shell
#!/bin/bash
if [[ ! `pidof -s term3_sim.x86_64` ]]; then
    /home/yubrshen/ai-study/sdc/term3/linux_sys_int/system_integration.x86_64
fi
#+END_SRC

Note, one need to customize for the path for the simulator executable.

   Eventually, after the working of dbw_node, we should see the car's movement in the simulator.

** Experience sharing

   It's quite time consuming to fix bugs, as there are a lots of print-outs in the shell for Waypoint_Updater, one has to
scroll back to figure out what when wrong. Often, only one error would be reported, and one has to repeat the above work-flow for
every iterations.

If you know bettor work-flow or tools, please share.

** messages involved
*** Message types

**** geometry_msgs/PoseStamped

     #+BEGIN_EXAMPLE
     $ rosmsg info geometry_msgs/PoseStamped
     std_msgs/Header header
     uint32 seq
     time stamp
     string frame_id
     geometry_msgs/Pose pose
     geometry_msgs/Point position
     float64 x
     float64 y
     float64 z
     geometry_msgs/Quaternion orientation
     float64 x
     float64 y
     float64 z
     float64 w

     #+END_EXAMPLE
     Characterize the position and orientation of a waypoint, used in styx_msg/Lane for waypoints

     Example of access/manipulation in Python:

     See the example for styx_msgs/Lane.

**** styx_msgs/Lane
     List of waypoints, used to for /base_waypoints and /final_waypoints

     #+BEGIN_EXAMPLE
     std_msgs/Header header
     uint32 seq
     time stamp
     string frame_id
     styx_msgs/Waypoint[] waypoints
     geometry_msgs/PoseStamped pose
     std_msgs/Header header
     uint32 seq
     time stamp
     string frame_id
     geometry_msgs/Pose pose
     geometry_msgs/Point position
     float64 x
     float64 y
     float64 z
     geometry_msgs/Quaternion orientation
     float64 x
     float64 y
     float64 z
     float64 w
     geometry_msgs/TwistStamped twist
     std_msgs/Header header
     uint32 seq
     time stamp
     string frame_id
     geometry_msgs/Twist twist
     geometry_msgs/Vector3 linear
     float64 x
     float64 y
     float64 z
     geometry_msgs/Vector3 angular
     float64 x
     float64 y
     float64 z
     #+END_EXAMPLE

     Example of access/manipulation in Python:

     #+NAME:
     #+BEGIN_SRC python :noweb yes :tangle :exports none
       // my_lane_msg is of type styx_msgs/Lane
       // The geometry_msgs/PoseStamped component:
       my_lane_msg[0].pose
       // The x coordinate of the position of the waypoint:
       my_lane_msg[0].pose.position.x
       // The w orientation at the position of the waypoint:
       my_lane_msg[0].pose.orientation.w

       // for the x direction linear velocity:
       my_lane_msg[0].twist.twist.linear.x
     #+END_SRC

*** /base_waypoints : input

    All the waypoints on the track.
    Note, this is only published once, so it must be stored by the Waypoint_Updater.

*** /current_pose : input

    The current position of the car, with orientation.

*** /final_waypoints : output

    The positions to be for the car after the current position, with the specified speed in
    the fields of twist.

    We only need to set the speed for the linear.x dimension. It's based on the information: [[https://discussions.udacity.com/t/what-is-the-meaning-of-the-various-waypoint-fields/406030/2][waypoint field definitions]]

    The angular speed on z dimension might be needed for turning? Not quite sure about it.

** Design Sketch for producing final_wayponts

   1. Subscribe for /base_points to get all the available waypoints
      Note: need to store the base_points, as it's only published once.

   2. Subscribe for /current_pose to trigger the generation of the final_waypoints (waypoints forward) up to LOOKAHEAD_WPS

      Here is the algorithm to generate:
      - only select those that are ahead of the current_pose

      - determine the speed required for the selected waypoints

      - published the computed waypoint forward to /final_waypoints

   3. How to tell if a waypont is ahead of the my_car, given my_car's position.

   Convert the waypoint's global coordinates to my_car's coordinates, waypoint_local_x, waypoint_local_y,
   if 0 <= waypoint_local_x, and the angle between the local_x-axis (my_car's orientation)
   and the line from the local coordinate origin (my_car's current position) to the waypoint's coordinates is not too large,
   that is, it's not too much of side-way movement.
then the waypoint is front of my_car.

   Those eligible waypoints should be sorted increasing by waypoint_local_x value, for the same waypoint_local_x,
   only choose the one with the smallest waypont_local_y.

   I'm not clear whether it's OK to miss some waypoints along the path of my_car in the publishing the /final_points?
   For example, there are waypoints on the track ahead of my_car, A, B, C, is it OK to just publish A, and C?  For example, for some reason, by program consider B is not a valid waypoint ahead.

*** to convert a global coordinates to local coordinates:
    It's based on the wiki:
    https://en.wikipedia.org/wiki/Rotation_matrix

    This implementation assumes the rotation has positive value from the global x-axis to the local x-axis
    counter-clockwise.

   #+NAME:to_local_coordinates
   #+BEGIN_SRC python :noweb tangle :tangle
     def to_local_coordinates(local_origin_x, local_origin_y, rotation, x, y):
         """
         compute the local coordinates for the global x, y coordinates values,
         given the local_origin_x, local_origin_y, and the rotation of the local x-axis.
         Assume the rotation is radius
         """
         shift_x = x - local_origin_x
         shift_y = y - local_origin_y

         cos_rotation = math.cos(rotation)
         sin_rotation = math.sin(rotation)

         local_x = cos_rotation*shift_x + sin_rotation*shift_y
         local_y = sin_rotation*shift_x + cos_rotation*shift_y

         return local_x, local_y
   #+END_SRC


*** How to calculate my_car's yaw angle, given its orientation in quaternion:

       The unit of the returned value is in radius?
       To check the documentation of transformations.euler_from_quaternion

 #+NAME:get_yaw
 #+BEGIN_SRC python :noweb tangle :tangle
   import tf                       # This is of ROS geometry, not of TensorFlow!
   def get_yaw(orientation):
       """
       Compute yaw from orientation, which is in Quaternion.
       """
       # orientation = msg.pose.orientation
       euler = tf.transformations.euler_from_quaternion([
           orientation.x,
           orientation.y,
           orientation.z,
           orientation.w])
       yaw = euler[2]
       return yaw
 #+END_SRC

** Code construction

   This section provides the detailed design and construction of the code for Waypoint_Updater.

*** subscribe and process /base_waypoints

    - Subscribe to /base_waypoint has been done in the __init__
    - implement the callback to store it and declare its availability.
    - compute the distance between the waypoints stored into an array self.distance_next ::
    the i_th element is the distance from the i_th waypoint to the (i+1)_th waypoint.
    - also record the longest and shortest distance to neighbor, and the indices
    - record the last closest waypoint in front in terms of index, in order to save the effort to find the next
    - 11/7 ::
              Remove the distance calculation not really needed for now, to save computing.

#+NAME:waypoints_cb
#+BEGIN_SRC python :noweb tangle :tangle
  def waypoints_cb(self, waypoints):
    # DONE: Implement
    if self.base_waypoints is None:
      self.base_waypoints = waypoints.waypoints
      self.base_waypoints_length = len(self.base_waypoints)
      # process the waypoints here
      # self.dist_to_next = []
      # dist = (distance_two_indices(self.base_waypoints, 0, 1))
      # self.dist_to_next.append(dist)
      # self.longest_dist, self.shortest_dist = dist, dist
      # self.longest_dist_index, self.shortest_dist_index = 0, 0

      # for i in range(1, len(self.base_waypoints)):
      #   dist = (distance_two_indices(self.base_waypoints, i, (i+1) % self.base_waypoints_length))
      #   self.dist_to_next.append(dist)
      #   if dist < self.shortest_dist:
      #     self.shortest_dist = dist
      #     self.shortest_dist_index = i
      #   # end of if dist < self.shortest_dist
      #   if self.longest_dist < dist:
      #     self.longest_dist = dist
      #     self.longegst_dist_index = dist
      #   # end of if self.longest_dist < dist

      # unsubscribe to the waypoint messages, no longer needed
      self.subscriber_waypoints.unregister()
      self.subscriber_waypoints = None
    # end of if self.base_waypoints is None
#+END_SRC

*** subscribe and process /current_pose
    - Subscribe to /current_pose is done in __init__

    - 11/6 ::
    change pose_cb only update the self.pose message, moving the function of generating waypoints ahead to self.loop.
    This is to make the call back more time responsive to improve overall system predictability.
    Only accept message when Waypoint_Updater is ready to process, otherwise reject /current_pose update to avoid delay.

#+NAME:pose_cb
#+BEGIN_SRC python :noweb tangle :tangle

  def pose_cb(self, msg):
      # WORKING: Implement
      #
      if self.pose is None:       # ready to process message
          self.pose = msg
      # end of if self.pose is None
      # otherwise, the current message is being processed, rejected the coming message and expect to receive more updated next one.
#+END_SRC
*** loop

    The loop for processing the /current_pose message

    The design that the waypoints provided by the Waypoint_Uploader is consecutive, maintaining the geometry adjacency.

    Note, the generation for /final_waypoints may be conditional to the availability of the base_waypoints.

    The function may need other routine to compare between waypoints to determine if a waypoint is ahead of the current_pose within the LOOKAHEAD_WPS

    also compute the desired velocity for the eligible waypoints.

    try to control the time of looking ahead instead of just control the number of look ahead waypoints.
    to be adaptive so that it does not waste computing resource to produce too many waypoints.

    On Nov. 3, I experimented that the waypoints ahead generation can be simplified as follows
    without any negative impact:
    - no more angle checking
    - no more sorted needed


#+NAME:loop
#+BEGIN_SRC python :noweb tangle :tangle
  import math

  def loop(self):
      rate = rospy.Rate(self.loop_freq)
      while not rospy.is_shutdown():
          if self.base_waypoints and self.pose:
              <<process-pose>>
              self.pose = None        # indicating this message has been processed
          # end of if self.base_waypoints and self.pose
          rate.sleep()
      # end of while not rospy.is_shutdow()
#+END_SRC

*** process-pose

Process one pose message in self.pose

First find the next closest waypoint in front of the vehicle.
Then use that to generate the rest of the final_waypoints.

#+NAME:process-pose
#+BEGIN_SRC python :noweb tangle :tangle
  current_pose = self.pose.pose.position
  current_orientation = self.pose.pose.orientation
  yaw = get_yaw(current_orientation)

  # Compute the waypoints ahead of the current_pose

  local_x = -1
  i = self.last_closest_front_waypoint_index - 1
  while (local_x <= 0):
    i = (i + 1) % self.base_waypoints_length
    waypoint = self.base_waypoints[i]
    w_pos = waypoint.pose.pose.position
    local_x, local_y = to_local_coordinates(current_pose.x, current_pose.y, yaw,
                                            w_pos.x, w_pos.y)
  # end of while (local_x < 0)

  # now i is the index of the closest waypoint in front
  self.last_closest_front_waypoint_index = i

  waypoints_count = 0
  lookahead_dist = 0  # the accumulated distance of the looking ahead
  lookahead_time = 0  # the lookahead time

  final_waypoints = []
  accumulated_turning = 0
  # modulize the code to be less dependent
  j = self.last_closest_front_waypoint_index
  while (# (lookahead_time < LOOKAHEAD_TIME_THRESHOLD) and
         (waypoints_count < LOOKAHEAD_WPS)):
    waypoint = copy.deepcopy(self.base_waypoints[j])
    j = (j + 1) % self.base_waypoints_length
    waypoints_count += 1
    turning_angle = math.atan2(local_y, local_x)
    accumulated_turning = (accumulated_turning + turning_angle) / waypoints_count
    # average accumulated turning

    estimated_vel = min(
        NORMAL_SPEED, SAEF_TURNING_SPEED +
        #(NORMAL_SPEED - SAEF_TURNING_SPEED)*math.exp(-3.5*abs(turning_angle)))
        (NORMAL_SPEED - SAEF_TURNING_SPEED)*math.exp(-3.9*abs(accumulated_turning)))

    waypoint.twist.twist.linear.x = estimated_vel # meter/s
    final_waypoints.append(waypoint)

    # dist_between = self.dist_to_next[(j - 1) % self.base_waypoints_length]
    # lookahead_dist += dist_between
    # lookahead_time = lookahead_dist / (estimated_vel)

    # prepare for the next iteration for estimating the turning angle, velocity
    current_waypoint = waypoint.pose.pose.position
    w_pos = self.base_waypoints[j].pose.pose.position  # the next waypoint after current_waypoint
    yaw = yaw + turning_angle
    local_x, local_y = to_local_coordinates(current_waypoint.x, current_waypoint.y, yaw,
                                            w_pos.x, w_pos.y)
  # end of while (LOOKAHEAD_TIME_THRESHOLD <= lookahead_time) or (LOOKAHEAD_WPS <= waypoints_count)
  rospy.loginfo('Lookahead threshold reached: waypoints_count: %d; lookahead_time: %d'
                % (waypoints_count, lookahead_time))

  # publish to /final_waypoints, need to package final_waypoints into Lane message
  publish_Lane(self.final_waypoints_pub, final_waypoints)
#+END_SRC


*** compare two pose, a and b, if a is ahead of b, considering the parameter of LOOKAHEAD_WPS

    Compare between two pose if one is ahead of the other within the range of LOOKAHEAD_WPS

    This problem is solved by converting the waypoint to the local coordinates of my_car.

*** select waypoints for /final_waypoints

    A loop or list expression to generate the list of eligible waypoints for /final_waypoints.
    It's implemented in the pose_cb.

*** determine the velocity for waypoints

    Compute the desired velocity for waypoints: for now, it's stab as constant. This is to be done (TBD).

*** Discussion on the appropriate value of LOOKAHEAD_WPS

    The value of LOOKAHEAD_WPS might impact the system work load. It should be sufficient large. But not too large.

*** Waypoint_Uploader integration

    This is the full source code for ./ros/src/waypoint_updater/waypoint_updater.py

    - 11/6 ::
    change LOOKAHEAD_TIME_THRESHOLD from 5 to 4 seconds, as I found that in pure_pursuit,
    it only look ahead about 20 meters, with velocity of 10 mps, it will only take about 2 seconds.
    So 4 seconds should be enough.

    - 11/6 ::
    add queue_size=1 to both Subscriber to /current_pose and /base_waypoints. This is to limit to process the most recent message.
    Any message that Waypoint_Update has no time to update would be discarded.

    - 11/6 ::
    Change the logic of processing /current_pose from call_back to separate loop to ensure regular time interval processing.

#+NAME:waypont_updater
#+BEGIN_SRC python :noweb tangle :tangle ./ros/src/waypoint_updater/waypoint_updater.py
  #!/usr/bin/env python

  import rospy

  import copy                     # for deepcopy
  from geometry_msgs.msg import PoseStamped
  from styx_msgs.msg import Lane, Waypoint

  import math

  '''
  This node will publish waypoints from the car's current position to some `x` distance ahead.

  As mentioned in the doc, you should ideally first implement a version which does not care
  about traffic lights or obstacles.

  Once you have created dbw_node, you will update this node to use the status of traffic lights too.

  Please note that our simulator also provides the exact location of traffic lights and their
  current status in `/vehicle/traffic_lights` message. You can use this message to build this node
  as well as to verify your TL classifier.

  - 11/7 ::
  add self.last_closest_front_waypoint_index to record the index of last the closet waypoint in front of the vehicle.
  This would be the index to search next time, to save computing. (Beware of index wrapping in index increment arithmetic!)

  - 11/7 ::
  reduce LOOKAHEAD_WPS to 50 and do away from distance calculation to save computing effort. It seems that 50 is enough
  for normal driving.

  - 11/8 ::
  Need to consider to reduce the speed when there is significant turn.

  How to characterize the turn? I might use the local coordinate transformation.
  Relative to a waypoint A, From the next waypoint's coordinates, x, y in the local coordinate of A,
  one can compute the angle between A's x-axis, and the direction AB by atan2(y, x). The larger the angle,
  the sharper the turn at A would be, so the speed at the A should be reduced.

  I may just calculate just the first a few, say 5 from the closest waypoint in front to save computing effort.

  TODO (for Yousuf and Aaron): Stopline location for each traffic light.
  '''

  LOOKAHEAD_WPS = 30 # 200 # Number of waypoints we will publish. You can change this number
  LOOKAHEAD_TIME_THRESHOLD = 4 # seconds, change from 5 to 4
  SAEF_TURNING_SPEED = 3.0       # meters/second
  NORMAL_SPEED = 30  # the normal speed of the car

  DANGER_TURNING_ANGLE = math.pi/4  # 30 degree

  <<get_yaw>>
  <<to_local_coordinates>>
  <<publish_Lane>>
  <<distance_two_indices>>

  class WaypointUpdater(object):
      def __init__(self):
          rospy.init_node('waypoint_updater')

          self.loop_freq = rospy.get_param('~loop_freq', 2)
          # the frequency to process vehicle messages

          rospy.Subscriber('/current_pose', PoseStamped, self.pose_cb, queue_size=1)
          self.subscriber_waypoints = rospy.Subscriber('/base_waypoints', Lane, self.waypoints_cb, queue_size=1)

          # TODO: Add a subscriber for /traffic_waypoint and /obstacle_waypoint below


          self.final_waypoints_pub = rospy.Publisher('final_waypoints', Lane, queue_size=1)

          # TODO: Add other member variables you need below

          self.base_waypoints = None  # indicating the base_waypoints is not yet available
          self.pose = None            # indicating that there is no message to process

          self.last_closest_front_waypoint_index = 0

          self.loop()
          #rospy.spin()

      <<loop>>

      <<pose_cb>>

      <<waypoints_cb>>

      <<traffic_cb>>

      <<obstacle_cb>>

      <<support_functions>>

  if __name__ == '__main__':
      try:
          WaypointUpdater()
      except rospy.ROSInterruptException:
          rospy.logerr('Could not start waypoint updater node.')

#+END_SRC

    Putting the code together for Waypoint_Uploader

* Other use cases

#+NAME:traffic_cb
#+BEGIN_SRC python :noweb tangle :tangle
def traffic_cb(self, msg):
        # TODO: Callback for /traffic_waypoint message. Implement
        pass

#+END_SRC

#+NAME:obstacle_cb
#+BEGIN_SRC python :noweb tangle :tangle
def obstacle_cb(self, msg):
        # TODO: Callback for /obstacle_waypoint message. We will implement it later
        pass

#+END_SRC

* Support functions

#+NAME:distance_two_indices
#+BEGIN_SRC python :noweb tangle :tangle
  def distance_two_indices(waypoints, i, j):
    a = waypoints[i].pose.pose.position
    b = waypoints[j].pose.pose.position
    return math.sqrt((a.x-b.x)**2 + (a.y-b.y)**2  + (a.z-b.z)**2)
#+END_SRC

#+NAME:publish_Lane
#+BEGIN_SRC python :noweb tangle :tangle
def publish_Lane(publisher, waypoints):
        lane = Lane()
        lane.header.frame_id = '/world'
        lane.header.stamp = rospy.Time(0)
        lane.waypoints = waypoints
        publisher.publish(lane)
#+END_SRC

#+NAME:support_functions
#+BEGIN_SRC python :noweb tangle :tangle
  def get_waypoint_velocity(self, waypoint):
          return waypoint.twist.twist.linear.x

  def set_waypoint_velocity(self, waypoints, waypoint, velocity):
          waypoints[waypoint].twist.twist.linear.x = velocity

  def distance(self, waypoints, wp1, wp2):
          dist = 0
          dl = lambda a, b: math.sqrt((a.x-b.x)**2 + (a.y-b.y)**2  + (a.z-b.z)**2)
          for i in range(wp1, wp2+1):
              dist += dl(waypoints[wp1].pose.pose.position, waypoints[i].pose.pose.position)
              wp1 = i
          return dist
#+END_SRC
