camera_info:
  focal_length_x: 1345.200806
  focal_length_y: 1353.838257
  image_width: 800
  image_height: 600
stop_line_positions:
    - [8.0, 16.2]
is_sim: false
bypass_light_classify: false

force_to_yellow: false
model: "light_classification/model/ssd_inception_real_world_20k/frozen_inference_graph.pb"
