camera_info:
  focal_length_x: 1345.200806
  focal_length_y: 1353.838257
  image_width: 800
  image_height: 600
stop_line_positions:
    - [8.0, 16.2]
traffic_light_detection:
  model: 'light_classification/site_frozen_inference_graph.pb'
  label_map: 'light_classification/label_map.pbtxt'
